In [7]:
import pandas as pd

df = pd.read_csv("../data/output/edger_results.csv")

condition = (df['24WT1_H9'] >= 5) & \
            (df['24WT2_A1'] >= 5) & \
            (df['24WT3_H11'] >= 5) & \
            (df['24PKLKO1_A2'] >= 5) & \
            (df['24PKLKO2_H10'] >= 5) & \
            (df['24PKLKO3_H12'] >= 5)

df = df[condition]
df.to_csv("../data/output/edger_results.csv", index=False)

In [1]:
import pandas as pd

df = pd.read_csv("../data/output/edger_results.csv")

condition = ((df['log2FoldChange'] >= 0.5) | (df['log2FoldChange'] <= -0.5)) & \
            (df['24WT1_H9'] >= 5) & \
            (df['24WT2_A1'] >= 5) & \
            (df['24WT3_H11'] >= 5) & \
            (df['24PKLKO1_A2'] >= 5) & \
            (df['24PKLKO2_H10'] >= 5) & \
            (df['24PKLKO3_H12'] >= 5) & \
            (df['FDR'] < 0.05)

df = df[condition]
df.to_csv("../data/output/edger_filtered_results.csv", index=False)
edger_genes = set(df["name"])
df

,name,baseMean,baseMeanA,baseMeanB,foldChange,log2FoldChange,logCPM,PValue,PAdj,FDR,falsePos,24WT1_H9,24WT2_A1,24WT3_H11,24PKLKO1_A2,24PKLKO2_H10,24PKLKO3_H12
0,PBANKA_0317141,408.333333,360.333333,48.000000,0.131861,-2.922912,4.611984,4.840525e-21,2.538855e-17,2.538855e-17,2.538855e-17,337,326,418,41,62,41
1,PBANKA_1329500,909.000000,774.333333,134.666667,0.174522,-2.518518,5.755312,9.112522e-17,4.778607e-13,2.389759e-13,4.779518e-13,894,503,926,123,116,165
2,PBANKA_1246600,164.000000,143.333333,20.666667,0.145512,-2.780792,3.327790,1.861957e-13,9.762242e-10,3.255322e-10,9.765965e-10,119,122,189,25,15,22
3,PBANKA_0300100,194.333333,173.666667,20.666667,0.119629,-3.063358,3.567710,4.073527e-13,2.135343e-09,5.341412e-10,2.136565e-09,156,110,255,27,19,16
4,PBANKA_1200096,138.666667,115.333333,23.333333,0.203956,-2.293672,3.087135,3.337853e-10,1.749369e-06,3.501408e-07,1.750704e-06,122,83,141,24,21,25
5,PBANKA_0317161,75.333333,68.333333,7.000000,0.109780,-3.187310,2.272996,4.315273e-10,2.261203e-06,3.772268e-07,2.263361e-06,55,42,108,8,5,8
6,PBANKA_1400400,166.333333,129.333333,37.000000,0.285568,-1.808095,3.341881,1.184382e-08,6.204977e-05,8.874405e-06,6.212083e-05,120,120,148,38,38,35
7,PBANKA_0216801,125.000000,26.000000,99.000000,3.791716,1.922851,2.924863,1.790030e-07,9.376176e-04,1.173588e-04,9.388706e-04,23,28,27,126,66,105
9,PBANKA_0306000,3371.000000,2593.333333,777.666667,0.299771,-1.738069,7.639100,5.294481e-07,2.772190e-03,2.776955e-04,2.776955e-03,2920,3041,1819,1175,760,398
11,PBANKA_0001001,179.333333,147.666667,31.666667,0.210985,-2.244785,3.448890,1.015885e-06,5.317140e-03,4.440263e-04,5.328315e-03,122,119,202,30,52,13
14,PBANKA_0836800,119.666667,91.333333,28.333333,0.309012,-1.694267,2.879200,7.230774e-06,3.782418e-02,2.528361e-03,3.792541e-02,107,65,102,23,38,24
15,PBANKA_1300096,56.666667,44.666667,12.000000,0.270417,-1.886740,1.874152,9.614366e-06,5.028313e-02,3.151709e-03,5.042735e-02,35,44,55,17,10,9
16,PBANKA_1227900,1999.333333,523.666667,1475.666667,2.818215,1.494782,6.886498,2.096385e-05,1.096200e-01,6.467966e-03,1.099554e-01,482,731,358,1034,1020,2373
18,PBANKA_1465700,109.666667,85.000000,24.666667,0.291422,-1.778818,2.749075,3.262584e-05,1.705353e-01,8.995626e-03,1.709169e-01,124,46,85,21,25,28
20,PBANKA_1239200,343.333333,95.333333,248.000000,2.598976,1.377943,4.359869,7.333847e-05,3.831935e-01,1.831716e-02,3.846603e-01,81,114,91,178,186,380
22,PBANKA_1349500,502.000000,149.000000,353.000000,2.368370,1.243895,4.900839,1.171229e-04,6.117328e-01,2.647042e-02,6.088197e-01,136,194,117,272,282,505
23,PBANKA_0515800,774.666667,218.333333,556.333333,2.548589,1.349699,5.523336,1.211230e-04,6.325043e-01,2.647042e-02,6.352901e-01,186,319,150,437,396,836
26,PBANKA_0412400,1144.333333,264.333333,880.000000,3.326735,1.734107,6.084303,1.765474e-04,9.214010e-01,3.429597e-02,9.259912e-01,202,453,138,481,613,1546
27,PBANKA_1207000,1476.000000,417.666667,1058.333333,2.535885,1.342489,6.449725,1.948517e-04,1.000000e+00,3.649991e-02,1.021997e+00,423,578,252,783,705,1687
28,PBANKA_1105800,494.000000,162.666667,331.333333,2.032439,1.023212,4.877793,2.091043e-04,1.000000e+00,3.781903e-02,1.096752e+00,153,190,145,284,300,410
29,PBANKA_1323800,873.000000,587.666667,285.333333,0.484079,-1.046686,5.695831,2.552928e-04,1.000000e+00,4.426809e-02,1.328043e+00,553,552,658,263,398,195
30,PBANKA_1315600,999.000000,316.333333,682.666667,2.160951,1.111666,5.888374,2.745285e-04,1.000000e+00,4.426809e-02,1.372311e+00,306,408,235,569,506,973
31,PBANKA_0620000,2136.666667,742.666667,1394.000000,1.878653,0.909698,6.982245,2.781132e-04,1.000000e+00,4.426809e-02,1.416579e+00,754,851,623,1253,1111,1818
32,PBANKA_0615100,1727.333333,511.666667,1215.666667,2.378189,1.249863,6.676521,2.785218e-04,1.000000e+00,4.426809e-02,1.460847e+00,444,701,390,990,729,1928
33,PBANKA_0804600,1051.666667,307.666667,744.000000,2.420433,1.275265,5.962704,2.941580e-04,1.000000e+00,4.446345e-02,1.511757e+00,270,430,223,537,510,1185
34,PBANKA_0613900,536.666667,151.666667,385.000000,2.546223,1.348359,4.996685,2.967056e-04,1.000000e+00,4.446345e-02,1.556221e+00,159,200,96,282,261,612
35,PBANKA_1213300,3225.000000,2131.333333,1093.666667,0.512703,-0.963804,7.575745,3.086281e-04,1.000000e+00,4.496540e-02,1.618754e+00,1515,2111,2768,1057,1344,880

In [2]:
edger_downreg = df[df["log2FoldChange"] < 0].reset_index(drop=True)
edger_downreg.to_csv("../data/output/edger_filtered_downreg.csv", index=False)
edger_downreg

,name,baseMean,baseMeanA,baseMeanB,foldChange,log2FoldChange,logCPM,PValue,PAdj,FDR,falsePos,24WT1_H9,24WT2_A1,24WT3_H11,24PKLKO1_A2,24PKLKO2_H10,24PKLKO3_H12
0,PBANKA_0317141,408.333333,360.333333,48.000000,0.131861,-2.922912,4.611984,4.840525e-21,2.538855e-17,2.538855e-17,2.538855e-17,337,326,418,41,62,41
1,PBANKA_1329500,909.000000,774.333333,134.666667,0.174522,-2.518518,5.755312,9.112522e-17,4.778607e-13,2.389759e-13,4.779518e-13,894,503,926,123,116,165
2,PBANKA_1246600,164.000000,143.333333,20.666667,0.145512,-2.780792,3.327790,1.861957e-13,9.762242e-10,3.255322e-10,9.765965e-10,119,122,189,25,15,22
3,PBANKA_0300100,194.333333,173.666667,20.666667,0.119629,-3.063358,3.567710,4.073527e-13,2.135343e-09,5.341412e-10,2.136565e-09,156,110,255,27,19,16
4,PBANKA_1200096,138.666667,115.333333,23.333333,0.203956,-2.293672,3.087135,3.337853e-10,1.749369e-06,3.501408e-07,1.750704e-06,122,83,141,24,21,25
5,PBANKA_0317161,75.333333,68.333333,7.000000,0.109780,-3.187310,2.272996,4.315273e-10,2.261203e-06,3.772268e-07,2.263361e-06,55,42,108,8,5,8
6,PBANKA_1400400,166.333333,129.333333,37.000000,0.285568,-1.808095,3.341881,1.184382e-08,6.204977e-05,8.874405e-06,6.212083e-05,120,120,148,38,38,35
7,PBANKA_0306000,3371.000000,2593.333333,777.666667,0.299771,-1.738069,7.639100,5.294481e-07,2.772190e-03,2.776955e-04,2.776955e-03,2920,3041,1819,1175,760,398
8,PBANKA_0001001,179.333333,147.666667,31.666667,0.210985,-2.244785,3.448890,1.015885e-06,5.317140e-03,4.440263e-04,5.328315e-03,122,119,202,30,52,13
9,PBANKA_0836800,119.666667,91.333333,28.333333,0.309012,-1.694267,2.879200,7.230774e-06,3.782418e-02,2.528361e-03,3.792541e-02,107,65,102,23,38,24
10,PBANKA_1300096,56.666667,44.666667,12.000000,0.270417,-1.886740,1.874152,9.614366e-06,5.028313e-02,3.151709e-03,5.042735e-02,35,44,55,17,10,9
11,PBANKA_1465700,109.666667,85.000000,24.666667,0.291422,-1.778818,2.749075,3.262584e-05,1.705353e-01,8.995626e-03,1.709169e-01,124,46,85,21,25,28
12,PBANKA_1323800,873.000000,587.666667,285.333333,0.484079,-1.046686,5.695831,2.552928e-04,1.000000e+00,4.426809e-02,1.328043e+00,553,552,658,263,398,195
13,PBANKA_1213300,3225.000000,2131.333333,1093.666667,0.512703,-0.963804,7.575745,3.086281e-04,1.000000e+00,4.496540e-02,1.618754e+00,1515,2111,2768,1057,1344,880

In [3]:
edger_upreg = df[df["log2FoldChange"] > 0].reset_index(drop=True)
edger_upreg.to_csv("../data/output/edger_filtered_upreg.csv", index=False)
edger_upreg

,name,baseMean,baseMeanA,baseMeanB,foldChange,log2FoldChange,logCPM,PValue,PAdj,FDR,falsePos,24WT1_H9,24WT2_A1,24WT3_H11,24PKLKO1_A2,24PKLKO2_H10,24PKLKO3_H12
0,PBANKA_0216801,125.000000,26.000000,99.000000,3.791716,1.922851,2.924863,1.790030e-07,0.000938,0.000117,0.000939,23,28,27,126,66,105
1,PBANKA_1227900,1999.333333,523.666667,1475.666667,2.818215,1.494782,6.886498,2.096385e-05,0.109620,0.006468,0.109955,482,731,358,1034,1020,2373
2,PBANKA_1239200,343.333333,95.333333,248.000000,2.598976,1.377943,4.359869,7.333847e-05,0.383193,0.018317,0.384660,81,114,91,178,186,380
3,PBANKA_1349500,502.000000,149.000000,353.000000,2.368370,1.243895,4.900839,1.171229e-04,0.611733,0.026470,0.608820,136,194,117,272,282,505
4,PBANKA_0515800,774.666667,218.333333,556.333333,2.548589,1.349699,5.523336,1.211230e-04,0.632504,0.026470,0.635290,186,319,150,437,396,836
5,PBANKA_0412400,1144.333333,264.333333,880.000000,3.326735,1.734107,6.084303,1.765474e-04,0.921401,0.034296,0.925991,202,453,138,481,613,1546
6,PBANKA_1207000,1476.000000,417.666667,1058.333333,2.535885,1.342489,6.449725,1.948517e-04,1.000000,0.036500,1.021997,423,578,252,783,705,1687
7,PBANKA_1105800,494.000000,162.666667,331.333333,2.032439,1.023212,4.877793,2.091043e-04,1.000000,0.037819,1.096752,153,190,145,284,300,410
8,PBANKA_1315600,999.000000,316.333333,682.666667,2.160951,1.111666,5.888374,2.745285e-04,1.000000,0.044268,1.372311,306,408,235,569,506,973
9,PBANKA_0620000,2136.666667,742.666667,1394.000000,1.878653,0.909698,6.982245,2.781132e-04,1.000000,0.044268,1.416579,754,851,623,1253,1111,1818
10,PBANKA_0615100,1727.333333,511.666667,1215.666667,2.378189,1.249863,6.676521,2.785218e-04,1.000000,0.044268,1.460847,444,701,390,990,729,1928
11,PBANKA_0804600,1051.666667,307.666667,744.000000,2.420433,1.275265,5.962704,2.941580e-04,1.000000,0.044463,1.511757,270,430,223,537,510,1185
12,PBANKA_0613900,536.666667,151.666667,385.000000,2.546223,1.348359,4.996685,2.967056e-04,1.000000,0.044463,1.556221,159,200,96,282,261,612

In [4]:
df = pd.read_csv("../data/output/deseq2_results.csv")

condition = ((df['log2FoldChange'] >= 0.5) | (df['log2FoldChange'] <= -0.5)) & \
            (df['24WT1_H9'] >= 5) & \
            (df['24WT2_A1'] >= 5) & \
            (df['24WT3_H11'] >= 5) & \
            (df['24PKLKO1_A2'] >= 5) & \
            (df['24PKLKO2_H10'] >= 5) & \
            (df['24PKLKO3_H12'] >= 5) & \
            (df['FDR'] < 0.05)

df = df[condition]
df.to_csv("../data/output/deseq2_filtered_results.csv", index=False)
deseq_genes = set(df["name"])
df

,name,baseMean,log2FoldChange,lfcSE,stat,PValue,FDR,baseMeanA,baseMeanB,foldChange,PValue_num,PAdj_hoc,24WT1_H9,24WT2_A1,24WT3_H11,24PKLKO1_A2,24PKLKO2_H10,24PKLKO3_H12
0,PBANKA_0317141,199.5,-2.921,0.282,-10.346,4.360000e-25,2.110000e-21,352.0,47.0,0.132,4.361899e-25,2.110000e-21,328.9,318.9,408.2,40.3,60.5,40.3
1,PBANKA_1329500,444.3,-2.514,0.293,-8.573,1.010000e-17,2.430000e-14,756.5,132.1,0.175,1.007303e-17,4.860000e-14,872.3,492.7,904.6,121.0,114.4,161.0
2,PBANKA_0300100,95.0,-3.064,0.411,-7.451,9.290000e-14,1.340000e-10,169.7,20.3,0.120,9.290512e-14,4.480000e-10,152.0,108.1,249.0,26.6,18.8,15.6
3,PBANKA_1246600,80.0,-2.782,0.375,-7.427,1.110000e-13,1.340000e-10,139.9,20.1,0.145,1.108637e-13,5.350000e-10,115.7,119.8,184.2,24.6,14.8,21.0
4,PBANKA_1200096,67.7,-2.294,0.370,-6.207,5.400000e-10,5.210000e-07,112.5,22.8,0.204,5.400885e-10,2.600000e-06,119.1,81.1,137.4,23.6,20.2,24.7
5,PBANKA_1400400,81.4,-1.805,0.310,-5.822,5.830000e-09,4.440000e-06,126.4,36.3,0.286,5.831637e-09,2.810000e-05,116.8,118.0,144.4,37.4,37.7,33.9
6,PBANKA_0317161,36.9,-3.203,0.552,-5.805,6.450000e-09,4.440000e-06,66.7,7.2,0.109,6.445883e-09,3.110000e-05,53.3,41.4,105.4,7.9,5.4,8.2
7,PBANKA_0216801,61.2,1.934,0.377,5.129,2.910000e-07,1.760000e-04,25.4,97.0,3.821,2.910890e-07,1.400000e-03,22.7,27.0,26.5,123.9,64.6,102.5
8,PBANKA_0001001,87.7,-2.241,0.445,-5.039,4.670000e-07,2.500000e-04,144.3,31.1,0.212,4.670230e-07,2.250000e-03,119.1,116.2,197.5,29.5,51.1,12.8
10,PBANKA_0306000,1650.0,-1.729,0.356,-4.852,1.220000e-06,5.360000e-04,2535.3,764.7,0.302,1.222401e-06,5.890000e-03,2850.5,2978.1,1777.2,1159.5,746.6,387.9
11,PBANKA_0836800,58.7,-1.691,0.385,-4.392,1.120000e-05,4.520000e-03,89.4,28.0,0.310,1.124116e-05,5.410000e-02,104.4,64.0,99.9,22.6,37.7,23.8
13,PBANKA_1227900,978.9,1.498,0.363,4.123,3.740000e-05,1.290000e-02,512.2,1445.7,2.825,3.744281e-05,1.800000e-01,470.7,716.1,349.7,1020.8,1002.3,2313.9
14,PBANKA_1465700,53.6,-1.778,0.439,-4.049,5.140000e-05,1.660000e-02,83.0,24.1,0.292,5.144503e-05,2.480000e-01,121.4,45.0,82.7,20.7,24.2,27.4
15,PBANKA_1239200,168.3,1.382,0.344,4.019,5.850000e-05,1.770000e-02,93.4,243.2,2.606,5.852711e-05,2.820000e-01,79.4,111.7,89.0,176.0,183.0,370.6
16,PBANKA_1105800,242.2,1.029,0.257,4.001,6.300000e-05,1.790000e-02,159.4,324.9,2.041,6.301956e-05,3.030000e-01,149.7,186.5,142.1,280.3,294.6,399.8
17,PBANKA_1349500,245.9,1.248,0.321,3.891,1.000000e-04,2.680000e-02,145.8,345.9,2.375,1.000371e-04,4.810000e-01,132.7,190.1,114.7,268.5,277.1,492.2
18,PBANKA_1300096,27.7,-1.890,0.495,-3.818,1.340000e-04,3.410000e-02,43.7,11.7,0.270,1.343762e-04,6.460000e-01,34.0,43.2,53.9,16.7,9.4,9.1
19,PBANKA_0515800,379.4,1.353,0.358,3.778,1.580000e-04,3.790000e-02,213.6,545.2,2.554,1.581653e-04,7.600000e-01,181.5,312.6,146.7,431.7,388.8,815.2
20,PBANKA_0412400,560.3,1.736,0.461,3.767,1.650000e-04,3.790000e-02,258.8,861.8,3.331,1.649083e-04,7.930000e-01,197.4,444.1,135.0,475.0,602.7,1507.8

In [5]:
inter = deseq_genes.intersection(edger_genes)
print("Num Deseq2 genes", len(deseq_genes))
print("Num EdgeR genes", len(edger_genes))
print(len(inter))
inter

Num Deseq2 genes 19
Num EdgeR genes 27
19

{'PBANKA_0001001',
 'PBANKA_0216801',
 'PBANKA_0300100',
 'PBANKA_0306000',
 'PBANKA_0317141',
 'PBANKA_0317161',
 'PBANKA_0412400',
 'PBANKA_0515800',
 'PBANKA_0836800',
 'PBANKA_1105800',
 'PBANKA_1200096',
 'PBANKA_1227900',
 'PBANKA_1239200',
 'PBANKA_1246600',
 'PBANKA_1300096',
 'PBANKA_1329500',
 'PBANKA_1349500',
 'PBANKA_1400400',
 'PBANKA_1465700'}

In [6]:
edger_genes - deseq_genes

{'PBANKA_0613900',
 'PBANKA_0615100',
 'PBANKA_0620000',
 'PBANKA_0804600',
 'PBANKA_1207000',
 'PBANKA_1213300',
 'PBANKA_1315600',
 'PBANKA_1323800'}